name: data_check
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pytest
  - hydra-core
  - matplotlib
  - pandas
  - jupyterlab
  - pip=23.3.1
  - pip:
      - mlflow
      - wandb==0.16.0
